### ISSUE TITLE
Fix FOIA link in Frame Generator

### ISSUE THREAD

**Issue by milanliu** [USGS-WiM/Styleguide#36]
FOIA link in frame generator is leading to file://www2.usgs.gov/foia/ instead of https://www.usgs.gov/foia. Sounds like this link might be broken on some more recently generated geonarrative index.html files - is there a way to blanket correct this without going in and updating each of the files?

**Comment by milanliu** [comment]
This is the only geonarrative I can find that is impacted, plus new index.html files generated: https://geonarrative.usgs.gov/grandbay/

**Comment by mitchas** [comment]
@milanliu  So I believe this is only an issue locally.

I had all the links set up as just `<a href="//www.usgs.gov...` without specifying the HTTP or HTTPS. This makes it default to whatever the site they're viewing it on uses. So if it's a secure https site, those links will open https.

It seems like it should have only been an issue if someone had opened a geonarative index.html file locally. So if they were viewing it in their browser and the URL was something like file://desktop/geonarratives/index.html - then the links defaulted to opening the same format, which was file://www.usgs.gov...

I updated the generator so the https is now hardcoded though, so it shouldn't happen any more.
