### ISSUE TITLE
Add USWDS banner to Frame Generator

### ISSUE THREAD

**Issue by milanliu** [USGS-WiM/Styleguide#37]
Request from Kaycee Faunce:

> There is currently little internal support for helping people successfully implement the U.S. Web Design System .gov domain banner on external-to-Drupal pages. I’ve helped several people add this to their geonarratives/web applications and have repeatedly heard that this is a need within the community. My understanding is that Digital Services is not planning on providing this support. The WIM geonarrative iframe generator is a popular tool – I think people would be deeply appreciative if WIM could add the USWDS banner to this template, as well. Not sure how much additional maintenance this would be for you all over time, but just a thought.

**Comment by mitchas** [comment]
@milanliu This is talking about the little "An official website of the United States government" banner, right?

I don't think that would be too difficult.

**Comment by milanliu** [comment]
@mitchas yes, it is! This one: https://designsystem.digital.gov/components/banner/

**Comment by mitchas** [comment]
This is now an option on the generator!
