### ISSUE TITLE
Add Dynamic QR Codes

### ISSUE THREAD

**Issue by milanliu** [USGS-WiM/Styleguide#40]
Received a request from Dawn Childs to add dynamic QR codes (user has ability to update link attached to a static QR code) to the Styleguide's QR code generator. Documenting as a future enhancement if there is time/interest.

**Comment by maggiejaenicke** [comment]
Moved to [GitLab](https://code.usgs.gov/WiM/wim-website/wim-styleguide/-/issues/2) since the repo has been migrated
