### ISSUE TITLE
Change marker location

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/Styleguide#41]
I'm not sure if this is the correct repo, but I think the markers may need to be moved slightly. Markers are centered on the coordinate, which means they are pointing to the incorrect location. We changed some of the markers.scss to move the markers slightly: https://code.usgs.gov/StreamStats/clients/StreamStats-National/-/commit/bb0689555f6d692ae38277f0f31c7f4d45ee2fef

**Comment by maggiejaenicke** [comment]
Moved to [GitLab](https://code.usgs.gov/WiM/wim-website/wim-styleguide/-/issues/1) since the repo has been migrated
